#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 04, 2018 02:01:45 AM IST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import loginpg_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    loginpg_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    loginpg_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {DejaVu Sans} -size 20 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("600x450+372+142")
        top.title("New Toplevel")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.033, rely=0.044, relheight=0.922
                , relwidth=0.942)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(width=565)

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.319, rely=0.024, height=35, width=191)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(font=font10)
        self.Label3.configure(text='''Update Room''')

        self.Button2_2 = tk.Button(self.Frame1)
        self.Button2_2.place(relx=0.142, rely=0.217, height=42, width=166)
        self.Button2_2.configure(activebackground="#f9f9f9")
        self.Button2_2.configure(background="#a0a0a0")
        self.Button2_2.configure(text='''USN''')
        self.Button2_2.configure(width=166)

        self.Button2_3 = tk.Button(self.Frame1)
        self.Button2_3.place(relx=0.142, rely=0.386, height=42, width=166)
        self.Button2_3.configure(activebackground="#f9f9f9")
        self.Button2_3.configure(background="#a0a0a0")
        self.Button2_3.configure(text='''Old Room No.''')

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.584, rely=0.217, relheight=0.101, relwidth=0.294)

        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(highlightbackground="#a0a0a0")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(width=166)
        self.Text1.configure(wrap='word')

        self.Text1_4 = tk.Text(self.Frame1)
        self.Text1_4.place(relx=0.584, rely=0.386, relheight=0.101
                , relwidth=0.294)
        self.Text1_4.configure(background="white")
        self.Text1_4.configure(font="TkTextFont")
        self.Text1_4.configure(selectbackground="#c4c4c4")
        self.Text1_4.configure(width=166)
        self.Text1_4.configure(wrap='word')

        self.Button2_3 = tk.Button(self.Frame1)
        self.Button2_3.place(relx=0.23, rely=0.699, height=42, width=136)
        self.Button2_3.configure(activebackground="#f9f9f9")
        self.Button2_3.configure(background="#a0a0a0")
        self.Button2_3.configure(text='''Update''')
        self.Button2_3.configure(width=136)

        self.Button2_3 = tk.Button(self.Frame1)
        self.Button2_3.place(relx=0.549, rely=0.699, height=42, width=136)
        self.Button2_3.configure(activebackground="#f9f9f9")
        self.Button2_3.configure(background="#a0a0a0")
        self.Button2_3.configure(text='''Cancel''')

        self.Button2_4 = tk.Button(self.Frame1)
        self.Button2_4.place(relx=0.142, rely=0.554, height=42, width=166)
        self.Button2_4.configure(activebackground="#f9f9f9")
        self.Button2_4.configure(background="#a0a0a0")
        self.Button2_4.configure(text='''New Room No.''')

        self.Text1_5 = tk.Text(self.Frame1)
        self.Text1_5.place(relx=0.584, rely=0.554, relheight=0.101
                , relwidth=0.294)
        self.Text1_5.configure(background="white")
        self.Text1_5.configure(font="TkTextFont")
        self.Text1_5.configure(selectbackground="#c4c4c4")
        self.Text1_5.configure(width=166)
        self.Text1_5.configure(wrap='word')

if __name__ == '__main__':
    vp_start_gui()





